### ISSUE TITLE
Issue in header with sails 0.12

### ISSUE THREAD

**Issue by etiennegauthier** [sails101/redis-session#3]
Hi

I've been trying to use redis as my session store and I keep getting this error: 
Error: ERR wrong number of arguments for \'set\' command\n   in _http_outgoing.js:350
followed by Error: Can't set headers after they are sent.
at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:350:11)
    at ServerResponse.res.setHeader (c:\repo.swmdigital.com.au\api.7rio2016.com.au\node_modules\sails\node_modules\express\node_modules\connect\lib\patch.js:134:22)
    at ServerResponse.res.set.res.header (c:\repo.swmdigital.com.au\api.7rio2016.com.au\node_modules\sails\node_modules\express\lib\response.js:595:10)
    at ServerResponse.res.contentType.res.type (c:\repo.swmdigital.com.au\api.7rio2016.com.au\node_modules\sails\node_modules\express\lib\response.js:462:15)
    at ServerResponse.res.send (c:\repo.swmdigital.com.au\api.7rio2016.com.au\node_modules\sails\node_modules\express\lib\response.js:128:14)
    at Immediate.<anonymous> (c:\repo.swmdigital.com.au\api.7rio2016.com.au\node_modules\sails\lib\hooks\http\get-configured-http-middleware-fns.js:84:24)
    at Immediate.immediate._onImmediate (timers.js:420:18)
    at processImmediate [as _immediateCallback](timers.js:368:17)

I was able to reproduce with a brand new generated app.

sails new MyTestApp. 
edit config/session.js and uncomment line the adapter line. 
sails lift
browse to localhost:1337 
and you get that error. 

Am I doing anything wrong? 

Thanks a lot. 
(I was able to run the sample redis-session successfully with sails 0.10, I'm working with the last version 0.12)

**Comment by etiennegauthier** [comment]
This is environment related (problem with windows and my redis server being too old). Not a sails problem.
